import { ScheduleItem } from "../../type/MessageTypes";
import { timeToMinutes, minutesToTime } from "@/utils/TimeFormatter";

export interface FixedAppointment {
	activity: string;
	start_time: string; // "HH:MM"
	end_time: string; // "HH:MM"
}

export interface FlexibleTask {
	activity: string;
	duration_minutes: number;
	priority?: number;
}

/**
 * ScheduleEngine – compiles a chronological schedule.
 *
 * It now respects the *break preference* (few-long / balanced / many-short) by
 *   • defining a maximum work‑block length per style
 *   • automatically splitting any flexible task that exceeds that block length
 *   • labeling each split as "(Part N)"
 *   • inserting a configurable break after **every** work block
 *   • inserting meals for personal schedules (optional via flag)
 *   • trimming excess minutes if the total activity time would overflow the free
 *     window (the last part is shortened accordingly).
 */
export class ScheduleEngine {
	/**
	 * Compiles a complete schedule.
	 * @param dayStart          Start of the day, e.g. "06:00"
	 * @param dayEnd            End of the day, e.g. "00:00"
	 * @param fixedAppointments Fixed appointments & meals (may be empty).
	 * @param flexibleTasks     Activities generated by the LLM.
	 * @param scheduleType      "event" or undefined (personal schedule).
	 * @param breakPreference   User's break style: "few-long", "balanced", "many-short".
	 */
	static compileSchedule(
		dayStart: string,
		dayEnd: string,
		fixedAppointments: FixedAppointment[],
		flexibleTasks: FlexibleTask[],
		scheduleType?: string,
		breakPreference: string = "balanced",
	): ScheduleItem[] {
		// ---------------------------------------------------------------------
		//  Prepare the fixed timeline (appointments + optional auto‑inserted meals)
		// ---------------------------------------------------------------------
		const startMins = timeToMinutes(dayStart);
		let endMins = timeToMinutes(dayEnd);
		if (endMins <= startMins) {
			endMins += 24 * 60; // handle overnight wrap‑around
		}

		// Insert meals for personal schedules only when requested.
		let fixed = [...fixedAppointments];
		if (scheduleType !== "event") {
			fixed = this.insertMeals(startMins, endMins, fixed, breakPreference);
		}

		// Normalise and sort fixed intervals.
		const sanitizedFixed = fixed
			.filter((f) => f.activity && f.start_time && f.end_time)
			.map((f) => {
				let start = timeToMinutes(f.start_time);
				let end = timeToMinutes(f.end_time);
				if (end <= start) end += 24 * 60;
				return { activity: f.activity, start, end };
			})
			.sort((a, b) => a.start - b.start);

		// ---------------------------------------------------------------------
		//   Determine the maximum work block length for the chosen break style.
		// ---------------------------------------------------------------------
		const maxBlock = this.maxBlockForBreakStyle(breakPreference);
		const breakLength = this.breakLengthForStyle(breakPreference);

		// ---------------------------------------------------------------------
		// Walk through the day, scheduling flexible tasks & breaks.
		// ---------------------------------------------------------------------
		const result: ScheduleItem[] = [];
		let currentTime = startMins;
		let fixedIdx = 0;

		for (const task of flexibleTasks) {
			// Skip malformed tasks early (Clean‑Code principle).
			if (task.duration_minutes <= 0) continue;

			// Schedule this task, automatically splitting when needed.
			this.splitAndScheduleTask(
				task,
				() => result,
				() => sanitizedFixed,
				() => currentTime,
				() => fixedIdx,
				() => endMins,
				maxBlock,
				breakLength, // new arg – length of each break
				(newTime) => (currentTime = newTime),
				(newIdx) => (fixedIdx = newIdx),
			);
		}

		// ---------------------------------------------------------------------
		//  Schedule any remaining fixed appointments (meals, etc.).
		// ---------------------------------------------------------------------
		while (fixedIdx < sanitizedFixed.length && currentTime < endMins) {
			const nextFixed = sanitizedFixed[fixedIdx];
			if (nextFixed.start >= currentTime) {
				if (nextFixed.start > currentTime) {
					result.push({
						activity: "Rest & Recovery",
						start_time: minutesToTime(currentTime % 1440),
						end_time: minutesToTime(nextFixed.start % 1440),
					});
				}
				result.push({
					activity: nextFixed.activity,
					start_time: minutesToTime(nextFixed.start % 1440),
					end_time: minutesToTime(nextFixed.end % 1440),
				});
				currentTime = nextFixed.end;
			}
			fixedIdx++;
		}

		// ---------------------------------------------------------------------
		//  Fill the rest of the day with a wind‑down block.
		// ---------------------------------------------------------------------
		if (currentTime < endMins) {
			result.push({
				activity: "Wind Down / Sleep Prep",
				start_time: minutesToTime(currentTime % 1440),
				end_time: minutesToTime(endMins % 1440),
			});
		}

		return result;
	}

	/** Maximum work block length (in minutes) for each break style. */
	private static maxBlockForBreakStyle(style: string): number {
		switch (style) {
			case "few-long":
				return 90; // ~1 h 30 min work, then a 15‑min break
			case "many-short":
				return 30; // short bursts
			case "balanced":
			default:
				return 60; // default balanced
		}
	}

	/** Break length (in minutes) for each break style. */
	private static breakLengthForStyle(style: string): number {
		const map: Record<string, number> = {
			"few-long": 15,
			balanced: 10,
			"many-short": 5,
		};
		return map[style] ?? 10;
	}

	/** Compute dynamic meal durations based on total day minutes and style. */
	private static computeMealDurations(
		dayMins: number,
		style: string,
	): { breakfast: number; lunch: number; dinner: number } {
		const breakfastPct: Record<string, number> = {
			"few-long": 0.07,
			balanced: 0.05,
			"many-short": 0.04,
		};
		const lunchPct: Record<string, number> = {
			"few-long": 0.06,
			balanced: 0.05,
			"many-short": 0.04,
		};
		const dinnerPct: Record<string, number> = {
			"few-long": 0.06,
			balanced: 0.05,
			"many-short": 0.04,
		};
		const bf = Math.max(
			15,
			Math.round(dayMins * (breakfastPct[style] ?? 0.05)),
		);
		const lu = Math.max(30, Math.round(dayMins * (lunchPct[style] ?? 0.05)));
		const di = Math.max(30, Math.round(dayMins * (dinnerPct[style] ?? 0.05)));
		return { breakfast: bf, lunch: lu, dinner: di };
	}

	// ---------------------------------------------------------------------
	// Existing helper – unchanged (insertMeals, etc.) – kept for compatibility.
	// ---------------------------------------------------------------------
	private static insertMeals(
		startMins: number,
		endMins: number,
		fixed: FixedAppointment[],
		breakPreference: string = "balanced",
	): FixedAppointment[] {
		const dayMins = endMins - startMins;
		const { breakfast, lunch, dinner } = this.computeMealDurations(
			dayMins,
			breakPreference,
		);

		const meals: FixedAppointment[] = [];

		// Breakfast – placed at day start.
		if (startMins + breakfast < endMins) {
			meals.push({
				activity: "Breakfast/Morning Routine",
				start_time: minutesToTime(startMins % 1440),
				end_time: minutesToTime((startMins + breakfast) % 1440),
			});
		}

		// Lunch – roughly halfway through the day.
		const lunchStart = Math.max(
			startMins + Math.round(dayMins * 0.5) - Math.round(lunch / 2),
			startMins,
		);
		if (lunchStart + lunch < endMins) {
			meals.push({
				activity: "Lunch",
				start_time: minutesToTime(lunchStart % 1440),
				end_time: minutesToTime((lunchStart + lunch) % 1440),
			});
		}

		// Dinner – near three‑quarters of the day.
		const dinnerStart = Math.max(
			startMins + Math.round(dayMins * 0.75),
			startMins,
		);
		if (dinnerStart + dinner < endMins) {
			meals.push({
				activity: "Dinner",
				start_time: minutesToTime(dinnerStart % 1440),
				end_time: minutesToTime((dinnerStart + dinner) % 1440),
			});
		}

		return [...fixed, ...meals];
	}

	/**
	 * Schedules a flexible task, splitting it into parts that respect the
	 * maximum block length and inserting breaks where appropriate.
	 *
	 * The function mutates `currentTime` and `fixedIdx` via the supplied setters
	 * so that the caller's loop variables stay in sync.
	 */
	private static splitAndScheduleTask(
		task: FlexibleTask,
		getResult: () => ScheduleItem[],
		getFixed: () => { activity: string; start: number; end: number }[],
		getCurrentTime: () => number,
		getFixedIdx: () => number,
		getEndMins: () => number,
		maxBlock: number,
		breakLength: number,
		setCurrentTime: (t: number) => void,
		setFixedIdx: (i: number) => void,
	) {
		let remaining = task.duration_minutes;
		let partIdx = 1;
		const result = getResult();
		const fixed = getFixed();

		while (remaining > 0) {
			const now = getCurrentTime();
			const endMins = getEndMins();

			// Find the next fixed appointment (or meal) after `now`.
			const nextFixed = fixed.find(
				(f, idx) => idx >= getFixedIdx() && f.start >= now,
			);

			// Compute how many minutes we can schedule before hitting the next fixed block.
			const available = nextFixed ? nextFixed.start - now : endMins - now;
			if (available <= 0) {
				// We are inside or exactly at a fixed appointment – fast‑forward.
				if (nextFixed) {
					result.push({
						activity: nextFixed.activity,
						start_time: minutesToTime(nextFixed.start % 1440),
						end_time: minutesToTime(nextFixed.end % 1440),
					});
					setCurrentTime(nextFixed.end);
					setFixedIdx(fixed.indexOf(nextFixed) + 1);
				}
				continue;
			}

			// Determine the chunk size: cannot exceed remaining task time,
			// the max block for the break style, or the time available before the next fixed appointment.
			const blockLimit = maxBlock;
			const chunk = Math.min(remaining, blockLimit, available);

			// Build a readable label – include part number only when we actually split.
			const label =
				remaining === task.duration_minutes && chunk === task.duration_minutes
					? task.activity
					: `${task.activity} (Part ${partIdx})`;

			result.push({
				activity: label,
				start_time: minutesToTime(now % 1440),
				end_time: minutesToTime((now + chunk) % 1440),
			});

			// Advance time.
			setCurrentTime(now + chunk);
			remaining -= chunk;

			// **Always** insert a break after the just‑finished chunk (if there is room).
			const afterChunk = getCurrentTime();
			const spaceForBreak = nextFixed
				? nextFixed.start - afterChunk
				: endMins - afterChunk;
			if (spaceForBreak >= breakLength) {
				result.push({
					activity: "Break",
					start_time: minutesToTime(afterChunk % 1440),
					end_time: minutesToTime(
						(afterChunk + breakLength) % 1440,
					),
				});
				setCurrentTime(afterChunk + breakLength);
			}

			partIdx++;
		}
	}
}
