/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alarm`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedules` | `/schedules`; params?: Router.UnknownInputParams; } | { pathname: `/schedule/add`; params?: Router.UnknownInputParams; } | { pathname: `/schedule/edit`; params?: Router.UnknownInputParams; } | { pathname: `/schedule/review`; params?: Router.UnknownInputParams; } | { pathname: `/schedule/schedule-conversation`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/alarm`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedules` | `/schedules`; params?: Router.UnknownOutputParams; } | { pathname: `/schedule/add`; params?: Router.UnknownOutputParams; } | { pathname: `/schedule/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/schedule/review`; params?: Router.UnknownOutputParams; } | { pathname: `/schedule/schedule-conversation`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/alarm${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedules${`?${string}` | `#${string}` | ''}` | `/schedules${`?${string}` | `#${string}` | ''}` | `/schedule/add${`?${string}` | `#${string}` | ''}` | `/schedule/edit${`?${string}` | `#${string}` | ''}` | `/schedule/review${`?${string}` | `#${string}` | ''}` | `/schedule/schedule-conversation${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alarm`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedules` | `/schedules`; params?: Router.UnknownInputParams; } | { pathname: `/schedule/add`; params?: Router.UnknownInputParams; } | { pathname: `/schedule/edit`; params?: Router.UnknownInputParams; } | { pathname: `/schedule/review`; params?: Router.UnknownInputParams; } | { pathname: `/schedule/schedule-conversation`; params?: Router.UnknownInputParams; };
    }
  }
}
